dev: true
chatgpt:
  key: ""
filter:
  ip:
    rate: 1
    size: 1
log:
  format: "2006-01-02 15:04:05"
  name: "log"
  path: "../log/"
  # 日志是否为json格式, 不填默认为经典格式
  json: true
  # 依次对应为 debug info warn error dpanic panic fatal
  level: info
wechat:
  gzh:
    secret:
    appid:
    token: