dev: true
chatgpt:
  key: 
    - "1"
filter:
  ip:
    # 每秒允许单个IP总访问数
    rate: 1
    size: 1
  request:
    # 每秒允许总访问数
    rate: 10
    size: 10
log:
  format: "2006-01-02 15:04:05"
  name: "log"
  path: "log/"
  # 日志是否为json格式, 不填默认为经典格式
  json: false
  # 依次对应为 debug info warn error dpanic panic fatal
  level: info
wechat:
  gzh:
    secret:
    appid:
    token:
database:
  mysql:
    uri: root:root@tcp(172.20.185.92:3306)/golang?charset=utf8mb4&parseTime=True&loc=Local
